module.exports = [
  {
    id: 1,
    name: "TV Samsung PL42A450",
    brand: "Samsung",
    inches: "42",
    type_screen: "PLASMA",
    price: 30000.0,
    url: "https://s.zst.com.br/cms-assets/2020/10/lcd-vs-led.png",
    description: "Ótima tv para ambientes pequenos como quarto de estudos",
  },
  {
    id: 2,
    name: "TV Sony XBR",
    brand: "Sony",
    inches: "42",
    type_screen: "LCD",
    price: 500.0,
    url: "https://s.zst.com.br/cms-assets/2021/02/design-sem-nome-79-.jpg",
    description: "Ótima tv para ambientes pequenos",
  },
  {
    id: 3,
    name: "Smart TV TCL S6500",
    brand: "TCL",
    inches: "32",
    type_screen: "LED",
    price: 100.0,
    url: "https://s.zst.com.br/cms-assets/2020/10/lcd-ou-led.png",
    description: "Ótima tv para ambientes pequenos como cozinha",
  },
  {
    id: 4,
    name: "Smart TV LG ThinQ AI 4K HDR",
    brand: "LG",
    inches: "55",
    type_screen: "OLED",
    price: 30000.0,
    url: "https://s.zst.com.br/cms-assets/2020/10/led-ou-lcd.png",
    description: "Ótima tv para ambientes grandes e iluminados",
  },
  {
    id: 5,
    name: "Smart TV LG ThinQ AI 4K HDR",
    brand: "LG",
    inches: "55",
    type_screen: "OLED",
    price: 30000.0,
    url: "https://s.zst.com.br/cms-assets/2020/10/led-ou-lcd.png",
    description: "Ótima tv para ambientes grandes e iluminados",
  },
  {
    id: 6,
    name: "Smart TV LG ThinQ AI 4K HDR",
    brand: "LG",
    inches: "55",
    type_screen: "OLED",
    price: 30000.0,
    url: "https://s.zst.com.br/cms-assets/2020/10/led-ou-lcd.png",
    description: "Ótima tv para ambientes grandes e iluminados",
  },
  {
    id: 7,
    name: "Smart TV TCL S6500",
    brand: "TCL",
    inches: "32",
    type_screen: "LED",
    price: 100.0,
    url: "https://s.zst.com.br/cms-assets/2020/10/lcd-ou-led.png",
    description: "Ótima tv para ambientes pequenos como cozinha",
  },
  {
    id: 8,
    name: "TV Samsung PL42A450",
    brand: "Samsung",
    inches: "42",
    type_screen: "PLASMA",
    price: 30000.0,
    url: "https://s.zst.com.br/cms-assets/2020/10/lcd-vs-led.png",
    description: "Ótima tv para ambientes pequenos como quarto de estudos",
  },
  {
    id: 9,
    name: "TV Sony XBR",
    brand: "Sony",
    inches: "42",
    type_screen: "LCD",
    price: 500.0,
    url: "https://s.zst.com.br/cms-assets/2021/02/design-sem-nome-79-.jpg",
    description: "Ótima tv para ambientes pequenos",
  },
  {
    id: 10,
    name: "TV Sony XBR",
    brand: "Sony",
    inches: "42",
    type_screen: "LCD",
    price: 500.0,
    url: "https://s.zst.com.br/cms-assets/2021/02/design-sem-nome-79-.jpg",
    description: "Ótima tv para ambientes pequenos",
  },
];
